INSERT INTO CUSTOMER (Id, Balance) VALUES (1, 8500);
INSERT INTO CUSTOMER (Id, Balance) VALUES (2, 6000);
INSERT INTO CUSTOMER (Id, Balance) VALUES (3, 8500);

INSERT INTO BOOK (Id, Price, Stock) VALUES (1, 85, 10);
INSERT INTO BOOK (id, Price, Stock) VALUES (2, 40, 60);
INSERT INTO BOOK (id, Price, Stock) VALUES (3, 80, 10);